### ISSUE TITLE
Get lists of Account (not lists including Account)

### ISSUE THREAD

**Issue by dknight212** [cran/rtoot#1]
Thanks so much for creating this package.

Is there any way to get the lists of an account (as opposed get_account_lists which gets lists which contain the account)?

For example, I want to get my lists so I can see who I have in each list.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
